### ISSUE TITLE
All answers flash after each answer is displayed

### ISSUE THREAD

**Issue by doyeap** [glutanimate/image-occlusion-enhanced#15]
For cards with non-overlapping occlusions, the answers flash when showing the answer or rating the difficulty. In other words, I briefly see the picture layer without the shapes for a fraction of a second whenever I press the spacebar. This doesn't happen every time but a definite majority of the time.
Using Anki 2.0.36
Using Image Occlusion Enhanced V0.2.3 
I am on OS X and I know you mentioned there may be issues but I am pretty new to both Anki and Image Occlusion and didn't know if there is an error I have made somewhere. 
Please let me know if there is anything I can do or if I should try Image Occlusion 2 (not enhanced)

Thank you very much

**Comment by Glutanimate** [comment]
Yep, this is one of the most frequent issues with Image Occlusion on OS X. It's the same across all versions of the add-on. If you look at this [archived](https://web.archive.org/web/20150416133311/https://ankiweb.net/shared/info/282798835) version of the original add-on page you'll see that the first reports concerning this problem date back to 2014. 

As far as I understand it it's a bug with how Anki's graphical toolkit (Qt) renders the cards on OS X. Well, that's my best guess at least. I don't have a Mac to test this out on and even if I had access to a machine I likely wouldn't be able to troubleshoot it because the problem lies deeper than the add-on itself.

Sadly I'm not aware of any workaround for this, so if anyone is reading this and knows how to solve this please feel free to contact me.

**Comment by doyeap** [comment]
Thank you

**Comment by glutanimate** [comment]
Closing this with the proviso that we still need to perform cross-platform tests (cf. https://github.com/glutanimate/image-occlusion-enhanced/projects/1#card-8246696).
