### ISSUE TITLE
Cards with the same image are hard to distinguish

### ISSUE THREAD

**Issue by aleksejrs** [Glutanimate/image-occlusion-enhanced#20]
https://github.com/Glutanimate/image-occlusion-enhanced/releases/tag/v1.0.0-beta1

The mask is too far below.

I am using [Multi-column note editor](https://ankiweb.net/shared/info/3491767031), but "Header" and "Footer" are next to the Image, so they become too tall.

So I repositioned the fields so that I have (shown in two columns):

* ID (hidden) — Single row (so that it doesn't become as tall as Image)
* Image; Question Mask
* Header; Footer
* Remarks; Sources
* Extra 1; Extra 2
* Answer Mask; Original Mask  (I don't know if looking at them is of any use)

**Comment by Glutanimate** [comment]
Hi,

thanks for testing the beta and sharing your thoughts on it.

Older versions of IO used to have the question mask as the first field, but this was more of a workaround against notes being marked as duplicates than a conscious design decision. With the question mask first, it was very hard to identify the content of each note, i.e. the image. That's why I restructured the field order in the latest release.

Of course you're free to rearrange the fields any way you want locally, but I'm afraid I can't change the default arrangement as this is the way most people requested the IO note type to work.

P.S.: Make sure to check out the [Maximum images height in card editor](https://ankiweb.net/shared/info/229181581) add-on. It might help with this somewhat.
