### ISSUE TITLE
Is there a way to create transparent 'questions'?

### ISSUE THREAD

**Issue by jonteamere** [Glutanimate/image-occlusion-enhanced#21]
I'd would really like to just HIGHLIGHT the image's label(s) while reviewing. Putting a colored box around each label would be nice OR even a colored underline would work.

Any thoughts on how to accomplish this?

**Comment by Glutanimate** [comment]
Hi Jonte,

just to make sure I'm reading you right: You want the question mask to be transparent with the label visible underneath while all the other masks stay solid and cover their labels?

If so, then I'm afraid that is not possible. IO automatically removes all transparency and opactity attributes from mask shapes currently. This is because, in the past, IO users would regularly have trouble with shapes becoming transparent and ruining their notes. OS X was the most prevalent platform where this happened. So I had to remove transparency entirely.

Now, there are a few ways you might be able to replicate what you're striving for without transparency. For instance, you could use the rectangle tool to draw a thin rectangle below each label. Or you could underline your labels with the line tool. Just try to experiment a bit with the tools provided by the masks and editor and you might find a workable solution.

Last, a quick note about this page: The Issues section on GitHub is mostly meant for technical issues and bugs in the add-on. As this is more of a general support question it would be better to post it in the [support thread](https://anki.tenderapp.com/discussions/add-ons/8295-image-occlusion-enhanced-official-thread) on the Anki forums. This makes it easier for other IO users to chime in and help you with your problem.

Cheers
Glutanimate
