### ISSUE TITLE
How do I add image in one of the field tabs?

### ISSUE THREAD

**Issue by rpc91** [glutanimate/image-occlusion-enhanced#37]
When I edit an existing I/O card, I can copy and paste a image into a field tab.
But when I try to add image in a field tab while creating a new I/O card, it doesn't let me.
Is that just how it is? Or am I doing something wrong?

Thanks!

**Comment by glutanimate** [comment]
Hi rpc,

the fields in the IO editor only support plain text. [Changing this is on my to-do list, but will require extensive work on the add-on](https://github.com/glutanimate/image-occlusion-enhanced/issues/8).

For now if you'd like to add in image you will have to do it by manually editing the note in the card browser. In order to apply the changes to all the notes that belong together you will have to first add the image to a field in question and then click on the image occlusion button. An editor window will come. Confirm that the image code is visible in the corresponding field by going to the fields tab. Then confirm your edit by clicking on "Edit note".

Hope that helps.
